### ISSUE TITLE
Idea for More Usernames

### ISSUE THREAD

**Issue by andrewboldi** [igleciasjoseph/InstagramBot#4]
What if we added last names as well? I have a json with 28k last names....

**Comment by igleciasjoseph** [comment]
What do you mean by last names?

Instagram takes one word as a 'username' variable

**Comment by andrewboldi** [comment]
Like Firstname: John and lastname: Smith.

Then the username would be something like "John_smith4729"

**Comment by igleciasjoseph** [comment]
Correct. Its a one word name.

**Comment by andrewboldi** [comment]
Yeah and adding more names would be helpful, right?
